export const AIRPORTS_BR = [
  { iataCode: 'CGH', name: 'Aeroporto de Congonhas', cityName: 'São Paulo', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'GRU', name: 'Aeroporto Internacional de Guarulhos', cityName: 'São Paulo', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'VCP', name: 'Aeroporto de Viracopos', cityName: 'Campinas', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'GIG', name: 'Aeroporto Internacional do Galeão', cityName: 'Rio de Janeiro', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'SDU', name: 'Aeroporto Santos Dumont', cityName: 'Rio de Janeiro', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'BSB', name: 'Aeroporto Internacional de Brasília', cityName: 'Brasília', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'SSA', name: 'Aeroporto Internacional de Salvador', cityName: 'Salvador', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'FOR', name: 'Aeroporto Internacional de Fortaleza', cityName: 'Fortaleza', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'REC', name: 'Aeroporto Internacional do Recife', cityName: 'Recife', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'POA', name: 'Aeroporto Internacional de Porto Alegre', cityName: 'Porto Alegre', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'CWB', name: 'Aeroporto Internacional de Curitiba', cityName: 'Curitiba', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'BEL', name: 'Aeroporto Internacional de Belém', cityName: 'Belém', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'MAO', name: 'Aeroporto Internacional de Manaus', cityName: 'Manaus', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'FLN', name: 'Aeroporto Internacional de Florianópolis', cityName: 'Florianópolis', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'NAT', name: 'Aeroporto Internacional de Natal', cityName: 'Natal', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'MCZ', name: 'Aeroporto Internacional de Maceió', cityName: 'Maceió', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'AJU', name: 'Aeroporto Internacional de Aracaju', cityName: 'Aracaju', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'THE', name: 'Aeroporto Internacional de Teresina', cityName: 'Teresina', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'SLZ', name: 'Aeroporto Internacional de São Luís', cityName: 'São Luís', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'CGB', name: 'Aeroporto Internacional de Cuiabá', cityName: 'Cuiabá', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'CGR', name: 'Aeroporto Internacional de Campo Grande', cityName: 'Campo Grande', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'PVH', name: 'Aeroporto Internacional de Porto Velho', cityName: 'Porto Velho', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'RBR', name: 'Aeroporto Internacional de Rio Branco', cityName: 'Rio Branco', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'PMW', name: 'Aeroporto Internacional de Palmas', cityName: 'Palmas', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'MAC', name: 'Aeroporto Internacional de Maceió', cityName: 'Maceió', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'GYN', name: 'Aeroporto de Goiânia', cityName: 'Goiânia', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'VIX', name: 'Aeroporto de Vitória', cityName: 'Vitória', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'BPS', name: 'Aeroporto de Porto Seguro', cityName: 'Porto Seguro', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'IOS', name: 'Aeroporto de Ilhéus', cityName: 'Ilhéus', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'JPA', name: 'Aeroporto Internacional de João Pessoa', cityName: 'João Pessoa', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'IGU', name: 'Aeroporto Internacional de Foz do Iguaçu', cityName: 'Foz do Iguaçu', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'LDB', name: 'Aeroporto de Londrina', cityName: 'Londrina', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'UDI', name: 'Aeroporto de Uberlândia', cityName: 'Uberlândia', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'BHZ', name: 'Aeroporto Internacional de Belo Horizonte', cityName: 'Belo Horizonte', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'CNF', name: 'Aeroporto Internacional Tancredo Neves', cityName: 'Belo Horizonte', countryName: 'Brasil', countryCode: 'BR' },
  { iataCode: 'PLU', name: 'Aeroporto da Pampulha', cityName: 'Belo Horizonte', countryName: 'Brasil', countryCode: 'BR' },
];